---
- hosts: all
  tasks:
  - name:    Install prerequisites
    apt:     name={{item}} update_cache=yes
    with_items:
     - apt-transport-https
     - ca-certificates
     - curl
     - software-properties-common
    tags:
         - packages
    become: yes
  - name:    Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    become: yes
  - name:    Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    become: yes
  - name:    Install Docker
    apt:     name=docker-ce
    become: yes

  - name: Add user to docker group
    user:
      name: ubuntu
      group: docker
    become: yes
  
  - name: Docker run
    shell: docker run -p 80:80 -d yolix/wwcode-hello-world:v5
    become: yes

  # - name: Create hello world container
  #   docker_container:
  #     name: hello-world
  #     image: yolix/wwcode-hello-world:v4
  #     ports:
  #       - "80:80"